### ISSUE TITLE
A question about copy/moving files from and to the mounted folder

### ISSUE THREAD

**Issue by cocodrino** [mwri/elixir-userfs#1]
Hi @mwri thanks for this project, seems really interesting so far, but I've a few questions, how you handle files copied to my filesystem??? are there any fuse function that handle this or must use a filewatcher, tracking the folder changes...

also if I move some file to outside my filesystem, how'd this work???

thank you so much...

Best regards...

**Comment by mwri** [comment]
There's nothing to stop you copying files out of the filesystem, the OS will in this case read files / directories (which would be serviced by your callback module) and write them to the destination. It's no different to copying files between any two directories or between any two filesystems or mounts.

There is no way you can copy files TO the filesystem though. The reason for this is that (currently) userfs / efuse implements only the FUSE operation callbacks required to implement a read only filesystem (which is just four operations (if you look at the [libfuse website (operations)](http://libfuse.github.io/doxygen/structfuse__operations.html) you will see there are about 40 or so in total). I don't know how many of these operations would be required for a basic read/write filesystem, probably not many more, but I've never required a read/write FUSE filesystem, so I've never gone there...

If userfs / efuse did provide those callbacks (which would not be enormously difficult probably, since they are really just passing the work on to the callback mainly, providing whatever marshalling of data is appropriate), then your filesystem would have to then provide the implementation for them to enable writes.
